INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Vanilla Sky', 'https://www.themoviedb.org/t/p/w1280/2nyj8JzNbsUY7tSzkDwFndU4bN5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Yesterday', 'https://www.themoviedb.org/t/p/w1280/1rjaRIAqFPQNnMtqSMLtg0VEABi.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Lista de Schindler', 'https://www.themoviedb.org/t/p/w1280/bGhhNzJYDsuLruNN5bJ2PvLcMiq.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Forrest Gump', 'https://www.themoviedb.org/t/p/w1280/bfeIonJ9AGC0kkNK0d69oIyqZMs.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Psicose', 'https://www.themoviedb.org/t/p/w1280/vNayuJV4gqtjhWeIeFYIO834rOd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Clube da Luta', 'https://www.themoviedb.org/t/p/w1280/m83Uwna5ohsLchpacgU3j8EtGhG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A culpa é das estrelas', 'https://www.themoviedb.org/t/p/w1280/nEbSB6eCozhIZZORPAlNQLDDPDG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Lobo de Wall Street', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Silencio dos Inocentes', 'https://www.themoviedb.org/t/p/w1280/paGUSTwcFrAxpGV1hSQ2wsI28id.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Lion: Uma Jornada para casa', 'https://www.themoviedb.org/t/p/w1280/svbUqOL9FdwCF9cKe4aEagVmteR.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Quem quer ser um milionário?', 'https://www.themoviedb.org/t/p/w1280/d8HmRSbytAkXgHV1oWQoiRC5usr.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O curioso caso de Bejamin Button', 'https://www.themoviedb.org/t/p/w1280/7fNRILGSHFzZ9BLUgkraGEHRaBb.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Encontro Marcado', 'https://www.themoviedb.org/t/p/w1280/9BgwZVj4lr7Se8R8VWaqGEUCZeJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Incrível história de Adaline', 'https://www.themoviedb.org/t/p/w1280/gU84OUm9c4R44Zx8U1YPbCzKqIo.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cisne Negro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hqh5O4KssfJWI62HGAgrjHXbxhD.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sem Limites', 'https://www.themoviedb.org/t/p/w1280/kg2IfJ4Mlmf7dRRdHCuckhWG8P6.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Clube da Luta', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hZkgoQYus5vegHoetLkCJzb17zJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O preço do amanhã', 'https://www.themoviedb.org/t/p/w1280/xuFZVPVebRrRwiH14uST8m4ulXj.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O advogado do Diabo', 'https://www.themoviedb.org/t/p/w1280/yzzcbbMnLcsvnMQWrhAfypTuEmU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Os outros', 'https://www.themoviedb.org/t/p/w1280/5dEa7JRjc5BuJPVQKsn9FpDZSIt.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Como se fosse a primeira vez', 'https://www.themoviedb.org/t/p/w1280/xbfB2yzfGIPKBDDFize1Y5acqjm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Sexto Sentido', 'https://www.themoviedb.org/t/p/w1280/ds7jw0WYCd6k7hBzMnzgFsTfg96.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Teoria de Tudo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kq2MHrRfH6RTfkvyDEmYLmGHE6U.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Uma Mente Brilhante', 'https://www.themoviedb.org/t/p/w1280/8K5W9QnNT7r1V9GuJ5z5KlrROkd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Gênio Indomável', 'https://www.themoviedb.org/t/p/w1280/AlXkMIEjvk2Npc15zyL0r3P4HBH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Interestelar', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Contato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'prenda-me se for capaz', 'https://www.themoviedb.org/t/p/w1280/pSaqcj3pwTKt34cyn6NrBE7V4eH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Baby Driver', 'https://www.themoviedb.org/t/p/w1280/1rYTtQ14rPB3KOgk5TjkUqiQFch.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Como eu era antes de você', 'https://www.themoviedb.org/t/p/w1280/1a60KPNTC4JKYphNQveAB37Lyif.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Diário de uma paixão', 'https://www.themoviedb.org/t/p/w1280/r1ttV3XhgryvmJMlBfpbzUfm6bG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Diabo veste Prada', 'https://www.themoviedb.org/t/p/w1280/fwaioeouE89lrcnckfluzIKMwSu.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Se beber, não case!', 'https://www.themoviedb.org/t/p/w1280/6Hi9g065cxrQc2TLh5zwmTOurvK.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);